<div class="alert alert-block alert-warning">
<span style="color: rgb(0,53,91);">
<center><img src="./Imagenes/ITESO_Logo.png" style="width:500px;height:142px;" title="Logo ITESO"></center>
<font face = "Times New Roman" size = "6"><b><center>Ingenierías ITESO</center></b></font>
<font face = "Times New Roman" size = "5"><b><center>Programación para Análisis de Datos</center></b></font>
<font face = "Times New Roman" size = "5"><center>Ejercicio 7: Agrupación de DataFrames de Pandas</center></font></b>
<div align="right"><font face = "Times New Roman" size = "2">Dr. Iván Esteban Villalón Turrubiates (villalon@iteso.mx)</font></div>
</span></div>

#### Nombre del Alumno: Santiago Nuñez Perez
#### Matrícula: 761552

#### Instrucciones:
Por favor, revisa cuidadosamente las siguientes instrucciones:

* Realiza este ejercicio de manera individual.
* Escribe tu nombre completo y matrícula en la celda correspondiente.
* Lee cuidadosamente cada uno de los ejercicios y realiza las acciones solicitadas.
* Coloca tu código ejecutable en las celdas debajo de la explicación de cada reactivo.
* Una vez terminado, sube en CANVAS sólamente el archivo `.ipynb` en la liga correspondiente.

#### Explicación:
Se cuenta con un grupo de datos que proporcionan información sobre la población de 3 municipios en el Estado de Jalisco, los cuales están en tres archivos `.CSV` donde cada uno de ellos contienen la siguiente información:

1. **Numero**: Es el número del del municipio que es parte del Estado.
2. **Municipio**: Es el nombre del municipio que es parte del Estado.
3. **Localidad**: Es el número de la localidad que es parte del municipio.
4. **Nombre Localidad**: Es el nombre de la localidad que es parte del municipio.
5. **Longitud**: Es el valor de la longitud para la coordenada de ubicación.
6. **Latitud**: Es el valor de la latitud para la coordenada de ubicación.
7. **Altitud**: Es el valor de la altitud para la coordenada de ubicación.
8. **Población**: Es la cantidad de población en cada localidad que es parte del municipio. 

Los archivos son:

1. El archivo `Jalisco_Mun01.csv` corresponde al municipio de Acatic.
2. El archivo `Jalisco_Mun02.csv` corresponde al municipio de Acatlán de Juárez.
3. El archivo `Jalisco_Mun03.csv` corresponde al municipio de Ahualulco de Mercado.

<center><img src="./Imagenes/INEGI_logo.png" style="width:350px;height:70px;" class="center"></center>

> Esta información es proporcionada por el Instituto Nacional de Estadística y Geografía (INEGI) como parte de su portal de datos abiertos, los cuales pueden ser consultados [en esta liga](https://www.inegi.org.mx/servicios/datosabiertos.html).

Para este ejercicio, se deben realizar el proceso de análisis por medio de los reactivos descritos a continuación, donde cada uno tiene un valor de **5 CRÉDITOS**, los cuales se agregarán al total acumulado de cada uno de los alumnos del curso.

**1.** Cargar las librerías **Pandas** y **Matplotlib**. Posteriormente, crear un **DataFrame** que contenga la concatenación de los tres archivos `.CSV` por medio de la aplicación del método `.concat()`, mostrando el contenido del **DataFrame** resultante a través de la función `display()`.

In [7]:
# Código del Reactivo 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Jalisco1 = pd.read_csv('.\Datos\Jalisco_Mun01.csv', names = ["Numero","Municipio","Localidad","Nombre" "Localidad","Longitud","Latitud","Altitud","Población"])
Jalisco2 = pd.read_csv('.\Datos\Jalisco_Mun02.csv', names = ["Numero","Municipio","Localidad","Nombre" "Localidad","Longitud","Latitud","Altitud","Población"])
Jalisco3 = pd.read_csv('.\Datos\Jalisco_Mun03.csv', names = ["Numero","Municipio","Localidad","Nombre" "Localidad","Longitud","Latitud","Altitud","Población"])

MovimientoNaranja = pd.concat([Jalisco1,Jalisco2,Jalisco3])

display(MovimientoNaranja)

,Numero,Municipio,Localidad,NombreLocalidad,Longitud,Latitud,Altitud,Población
0,Numero,Municipio,Localidad,Nombre Localidad,Longitud,Latitud,Altitud,Población
1,1,Acatic,1,Acatic,1025419,204646,1693,11890
2,1,Acatic,2,Agua Prieta (Tepetates),1025331,204737,1735,107
3,1,Acatic,3,Alacates,1025103,204925,1794,10
4,1,Acatic,6,El Bajío de los Herrera,1025849,204344,1708,36
...,...,...,...,...,...,...,...,...
24,3,Ahualulco de Mercado,86,Rancho Cuevas,1035928,204138,1333,3
25,3,Ahualulco de Mercado,96,El Trapiche,1035906,203830,1543,1
26,3,Ahualulco de Mercado,97,El Encanto,1035720,204206,1323,2
27,3,Ahualulco de Mercado,99,El Novillo,1035720,204157,1322,5
28,3,Ahualulco de Mercado,100,Loma Alta,1035558,204427,1375,1

**2.** Realizar un nuevo **DataFrame** que contenga solamente la información de las columnas `Municipio`, `Nombre Localidad` y `Población`, mostrando su contenido a través de la función `display()`.

In [ ]:
# Código del Reactivo 2
Miguel = MovimientoNaranja.groupby(['Municipio', 'NombreLocalidad', "Población"])
Miguel.head()

,Numero,Municipio,Localidad,NombreLocalidad,Longitud,Latitud,Altitud,Población
0,Numero,Municipio,Localidad,Nombre Localidad,Longitud,Latitud,Altitud,Población
1,1,Acatic,1,Acatic,1025419,204646,1693,11890
2,1,Acatic,2,Agua Prieta (Tepetates),1025331,204737,1735,107
3,1,Acatic,3,Alacates,1025103,204925,1794,10
4,1,Acatic,6,El Bajío de los Herrera,1025849,204344,1708,36
...,...,...,...,...,...,...,...,...
24,3,Ahualulco de Mercado,86,Rancho Cuevas,1035928,204138,1333,3
25,3,Ahualulco de Mercado,96,El Trapiche,1035906,203830,1543,1
26,3,Ahualulco de Mercado,97,El Encanto,1035720,204206,1323,2
27,3,Ahualulco de Mercado,99,El Novillo,1035720,204157,1322,5
28,3,Ahualulco de Mercado,100,Loma Alta,1035558,204427,1375,1

**3.** Realizar un nuevo **DataFrame** que contenga la agrupación por medio de la columna `Municipio` y muestre la suma de los valores de la población. Para ello se emplea el método `.groupby().sum()`, mostrando su contenido a través de la función `display()`.

In [3]:
# Código del Reactivo 3

**4.** A partir del **DataFrame** generado, realizar una gráfica que muestre los municipios y la cantidad de población en cada uno de ellos:

In [4]:
# Código del Reactivo 4

**5.** Realizar una ***tabla pivote*** a partir del **DataFrame** del *Reactivo 2* en base a la `Población ` y `Nombre Localidad`, la cual mostrará la lista de las localidades y sus respectivos valores de población.

In [5]:
# Código del Reactivo 5

<div class="alert alert-block alert-danger">
<b>.: Fin del Ejercicio 7 :.</b>
</div>